<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAhmpfof\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAhmpfof/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAhmpfof.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAhmpfof\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAhmpfof\appProdProjectContainer(array(
    'container.build_hash' => 'Ahmpfof',
    'container.build_id' => 'e461819a',
    'container.build_time' => 1559741889,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAhmpfof');
