<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJtbkapz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJtbkapz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJtbkapz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJtbkapz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJtbkapz\appProdProjectContainer(array(
    'container.build_hash' => 'Jtbkapz',
    'container.build_id' => '6ca00716',
    'container.build_time' => 1559741526,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJtbkapz');
